### ISSUE TITLE
ERROR Error handling request

### ISSUE THREAD

**Issue by KristijanL** [kairoaraujo/kodak-smart-home#5]
Hi,

i am trying to configure the integration but cant get it to work, if you could help me, what am i doing wrong?

using latest hass install as a docker container and latest kodak-smart-home, i configured

kodak_smart_home:
  username: !USERNAME!
  password: !PASSWORD!
  region: 'EU'

but get an error:

```
2021-07-11 06:55:13 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
2021-07-11 06:55:28 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
2021-07-11 06:55:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
2021-07-11 06:55:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
2021-07-11 06:55:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
2021-07-11 06:55:42 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
2021-07-11 06:55:42 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/kodak_smart_home/camera.py", line 158, in async_camera_image
    ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'
```

**Comment by kairoaraujo** [comment]
Hi @KristijanL, thank you for your bug report. I will have a look and try to reproduce it.
Could you please give the version of the home assistant docker image?

**Comment by kairoaraujo** [comment]
@KristijanL,
I have tested it. Can you try to test it for me?
Edit inside your ``custom_components/kodak_smart_home/camera.py`` lines ``178`` and ``158``.

Remove the ``loop`` parameter:

From
        ``ffmpeg = ImageFrame(self._ffmpeg.binary, loop=self.hass.loop)``
To
        ``ffmpeg = ImageFrame(self._ffmpeg.binary)``


From
        ``stream = CameraMjpeg(self._ffmpeg.binary, loop=self.hass.loop)``
To
        ``stream = CameraMjpeg(self._ffmpeg.binary)``

**Comment by KristijanL** [comment]
currently i am using this docker image
https://hub.docker.com/layers/homeassistant/raspberrypi3-homeassistant/stable/images/sha256-98d55d3a66e89a93f7ea42df98f35c398bf179b520b1832d894abb7f0fd2bdc6?context=explore

with applied changes, i don't get any errors, but still there is no picture.

![Screenshot 2021-07-12 at 17 04 43](https://user-images.githubusercontent.com/977481/125310957-542cee00-e333-11eb-84eb-9967ef4020d7.png)

**Comment by kairoaraujo** [comment]
Hi @KristijanL, thank you for your feedback.
I will need to investigate more.

**Comment by KristijanL** [comment]
Any news? Need more debug info?

**Comment by kairoaraujo** [comment]
> Any news? Need more debug info?

Hi @KristijanL, the latest release is working.
Do you have enabled the motion alerts in your camera? Because there is no live streaming, but it play the latest motion detected.
In your camera go to settings, Motion Detection.
